import React, { useEffect, useState } from "react";
import { Alert, ScrollView, Text } from "react-native";
import { Card, EmptyState, Loader, Screen, styles } from "../components/ui";
import { supabaseService } from "../services/supabaseService";

function useLoad(loader){ const [data,setData]=useState([]); const [loading,setLoading]=useState(true); useEffect(()=>{loader().then(setData).catch(e=>Alert.alert('Eroare',e.message)).finally(()=>setLoading(false))},[]); return {data,loading}; }
export function PlayersScreen(){ const {data,loading}=useLoad(()=>supabaseService.getPlayers()); return <Screen title="Jucători" subtitle="Listă separată de App.js"><ScrollView>{loading?<Loader/>:data.length?data.map(p=><Card key={p.id}><Text style={styles.h2}>#{p.no} {p.name}</Text><Text style={styles.p}>{p.role} • {p.group} • {p.status}</Text><Text style={styles.p}>Picior: {p.foot || '-'} | Medical: {p.medicalStatus || '-'}</Text></Card>):<EmptyState text="Nu sunt jucători sau nu ai acces."/>}</ScrollView></Screen> }
export function TrainingsScreen(){ const {data,loading}=useLoad(()=>supabaseService.getTrainings()); return <Screen title="Antrenamente"><ScrollView>{loading?<Loader/>:data.length?data.map(t=><Card key={t.id}><Text style={styles.h2}>{t.group} • {t.date}</Text><Text style={styles.p}>{t.time} • {t.location}</Text><Text style={styles.p}>Antrenor: {t.coach}</Text><Text style={styles.p}>{t.theme}</Text></Card>):<EmptyState text="Nu sunt antrenamente sau nu ai acces."/>}</ScrollView></Screen> }
export function MatchesScreen(){ const {data,loading}=useLoad(()=>supabaseService.getMatches()); return <Screen title="Meciuri"><ScrollView>{loading?<Loader/>:data.length?data.map(m=><Card key={m.id}><Text style={styles.h2}>{m.group} vs {m.opponent}</Text><Text style={styles.p}>{m.date} {m.time} • {m.location}</Text><Text style={styles.p}>{m.status} {m.score ? `• ${m.score}` : ''}</Text></Card>):<EmptyState text="Nu sunt meciuri sau nu ai acces."/>}</ScrollView></Screen> }
